# Best job.

- type: job
  id: ChiefMedicalOfficer
  name: job-name-cmo
  description: job-description-cmo
  playTimeTracker: JobChiefMedicalOfficer
  antagAdvantage: 6 # DeltaV - Reduced TC: Head of Staff
  requirements:
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 14400 # 4 hrs
  - !type:RoleTimeRequirement
    role: JobMedicalDoctor
    time: 14400 # 4 hrs
  - !type:RoleTimeRequirement
    role: JobParamedic
    time: 14400 # 4 hrs
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 36000 # 10 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Command roles
  weight: 10
  startingGear: CMOGear
  icon: "JobIconChiefMedicalOfficer"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - Medical
  - Command
  - Maintenance
  - Chemistry
  - ChiefMedicalOfficer
  - Paramedic # DeltaV - Add Paramedic access
  - External # DeltaV - Paramedics need this access
  - Psychologist # DeltaV - Add Psychologist access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: CMOGear
  equipment:
    id: CMOPDA
    ears: ClothingHeadsetCMO
    belt: ClothingBeltMedicalFilled
