- type: job
  id: SeniorPhysician
  name: job-name-senior-physician
  description: job-description-senior-physician
  playTimeTracker: JobSeniorPhysician
  setPreference: true # DeltaV - Readded Senior roles (removed upstream)
  canBeAntag: true # Echo Station: Yes, seniors can be antags.
  antagAdvantage: 6 # Echo Station: 14 TC. Medical supplies, chem access, paramedic access, ..
  requirements:
  - !type:RoleTimeRequirement
    role: JobChemist
    time: 21600 #6 hrs
  - !type:RoleTimeRequirement
    role: JobMedicalDoctor
    time: 43200 #12 hrs
  - !type:RoleTimeRequirement
    role: JobParamedic
    time: 21600 #6 hrs
  - !type:DepartmentTimeRequirement
    department: Medical
    time: 216000 # 60 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Senior roles
  startingGear: SeniorPhysicianGear
  icon: "JobIconSeniorPhysician"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Chemistry
  - Paramedic
  - External

- type: startingGear
  id: SeniorPhysicianGear
  equipment:
    id: SeniorPhysicianPDA
    ears: ClothingHeadsetMedical
    belt: ClothingBeltMedicalFilled
    innerClothingSkirt: ClothingUniformJumpskirtSeniorPhysician
    satchel: ClothingBackpackSatchelMedicalFilled
    duffelbag: ClothingBackpackDuffelMedicalFilled
