- type: job
  id: Detective
  name: job-name-detective
  description: job-description-detective
  playTimeTracker: JobDetective
  requirements:
    # Echo Station: Remove most time requirements
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 7200 # 2hrs
#    - !type:RoleTimeRequirement # DeltaV - JobSecurityOfficer time requirement
#      role: JobSecurityOfficer
#      time: 21600 # 6 hrs
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all security roles
  startingGear: DetectiveGear
  icon: "JobIconDetective"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  #- Service # Delta V: Access adjustments
  - Detective
  - Cryogenics # Delta V: Access adjustments
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: DetectiveGear
  equipment:
#    eyes: ClothingEyesGlassesSecurity # DeltaV
    id: DetectivePDA
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltHolsterFilled
