- type: job
  id: HeadOfSecurity
  name: job-name-hos
  description: job-description-hos
  playTimeTracker: JobHeadOfSecurity
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 36000 # 10 hours
  - !type:RoleTimeRequirement
    role: JobWarden
    time: 144000 # 4 hours
  - !type:DepartmentTimeRequirement
    department: Command
    time: 144000 # 4 hours
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all security roles
  whitelisted: true # Echo Station: Also require role specific whitelist
  weight: 10
  startingGear: HoSGear
  icon: "JobIconHeadOfSecurity"
  requireAdminNotify: true
  supervisors: job-supervisors-captain
  canBeAntag: false
  access:
  - HeadOfSecurity
  - Command
  #- Brig  # Delta V: Removed
  - Security
  - Armory
  - Maintenance
  #- Service # Delta V: Access adjustments
  - External
  - Detective
  - Corpsman # DeltaV - added Corpsman access
  - Cryogenics
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
  - !type:AddComponentSpecial
    components:
    - type: PsionicBonusChance #Nyano - Summary: makes it more likely to become psionic.
      flatBonus: 0.025

- type: startingGear
  id: HoSGear
  equipment:
    #    eyes: ClothingEyesGlassesSecurity # DeltaV
    id: HoSPDA
    gloves: ClothingHandsGlovesCombat
    ears: ClothingHeadsetAltSecurity
    pocket1: WeaponPistolMk58Nonlethal
