- type: job
  id: SeniorOfficer
  name: job-name-senior-officer
  description: job-description-senior-officer
  playTimeTracker: JobSeniorOfficer
  setPreference: true # DeltaV - Readded Senior roles (removed upstream)
  requirements:
  - !type:RoleTimeRequirement
    role: JobWarden
    time: 21600 #6 hrs
  - !type:RoleTimeRequirement
    role: JobDetective
    time: 7200 #2 hrs
  - !type:RoleTimeRequirement
    role: JobSecurityOfficer
    time: 21600 #6 hrs
  - !type:DepartmentTimeRequirement
    department: Security
    time: 216000 # 60 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all security roles
  startingGear: SeniorOfficerGear
  icon: "JobIconSeniorOfficer"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Security
  #- Brig # Delta V: Removed
  - Maintenance
  - Service
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: SeniorOfficerGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHeadHatBeretSecurity
    id: SeniorOfficerPDA
    ears: ClothingHeadsetSecurity
    pocket1: WeaponPistolMk58Nonlethal
    innerClothingSkirt: ClothingUniformJumpskirtSeniorOfficer
    satchel: ClothingBackpackSatchelSecurityFilled
    duffelbag: ClothingBackpackDuffelSecurityFilled
