- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  setPreference: true # DeltaV - Readded Senior roles (removed upstream)
  canBeAntag: true # Echo Station: Yes, seniors can be antags.
  antagAdvantage: 6 # Echo Station: 14 TC.
  requirements:
  - !type:RoleTimeRequirement
    role: JobAtmosphericTechnician
    time: 21600 #6 hrs
  - !type:RoleTimeRequirement
    role: JobStationEngineer
    time: 21600 #6 hrs
  - !type:DepartmentTimeRequirement
    department: Engineering
    time: 216000 # 60 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Senior roles
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
    innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
    satchel: ClothingBackpackSatchelEngineeringFilled
    duffelbag: ClothingBackpackDuffelEngineeringFilled
