- type: job
  id: Psychologist
  name: job-name-psychologist
  description: job-description-psychologist
  playTimeTracker: JobPsychologist
  requirements:
#    - !type:OverallPlaytimeRequirement # Echo Station - to prevent griefers from taking the role.
#      time: 14400 # 4 hours
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting
  startingGear: PsychologistGear
  icon: "JobIconPsychologist"
  supervisors: job-supervisors-cmo
  access:
  - Medical
  - Maintenance
  - Psychologist # DeltaV - Add Psychologist access
  extendedAccess:
  - Chemistry

- type: startingGear
  id: PsychologistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPsychologist
    shoes: ClothingShoesLeather
    id: PsychologistPDA
    ears: ClothingHeadsetMedical
    pocket1: RubberStampPsychologist
