- type: job
  id: Courier
  name: job-name-courier
  description: job-description-courier
  startingGear: CourierGear
  playTimeTracker: JobCourier
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 3600 # 1 hr
  icon: "JobIconCourier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: CourierGear
  equipment:
    ears: ClothingHeadsetCargo
    belt: CourierBag
