- type: job
  id: SalvageSpecialist
  name: job-name-salvagespec
  description: job-description-salvagespec
  playTimeTracker: JobSalvageSpecialist
  antagAdvantage: 8 # DeltaV - Reduced TC: External Access + Free hardsuit and weapons
  requirements:
  - !type:DepartmentTimeRequirement
    department: Logistics # DeltaV - Logistics Department replacing Cargo
    time: 21600 #DeltaV 6 hrs
  #  - !type:OverallPlaytimeRequirement #DeltaV
  #    time: 36000 #10 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting (access to weapons)
  icon: "JobIconShaftMiner"
  startingGear: SalvageSpecialistGear
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Salvage
  - Maintenance
  - External

- type: startingGear
  id: SalvageSpecialistGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitSalvageSpecialist
    id: SalvagePDA
    ears: ClothingHeadsetCargo
