- type: job
  id: Gladiator
  name: job-name-gladiator
  description: job-description-gladiator
  playTimeTracker: JobGladiator
  startingGear: NyanoGladiatorGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconGladiator"
  supervisors: job-supervisors-security
  setPreference: true
  #  whitelistRequired: true
  requirements:
  - !type:DepartmentTimeRequirement
    department: Security
    time: 21600
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting
  special:
  - !type:AddComponentSpecial
    components:
    - type: Boxer
      modifiers:
        coefficients: # These only apply to unarmed
          Blunt: 1.5
          Slash: 1.5
          Piercing: 1.5

- type: startingGear
  id: NyanoGladiatorGear
  equipment:
    id: GladiatorPDA
    ears: ClothingHeadsetGrey
  #any other possessions, spawn in cell
