- type: job
  id: PrisonGuard
  name: job-name-guard
  description: job-description-guard
  playTimeTracker: JobPrisonGuard
  requirements:
    # Echo Station: Remove most playtime requirements
#    - !type:OverallPlaytimeRequirement
#      time: 18000
#    - !type:DepartmentTimeRequirement
#      department: Security
#      time: 14400
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all security roles
  startingGear: PrisonGuardGear
  alwaysUseSpawner: true
  canBeAntag: false
  icon: "JobIconPrisonGuard"
  supervisors: job-supervisors-warden
  setPreference: true
#  whitelistRequired: true
  access:
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]


- type: startingGear
  id: PrisonGuardGear
  equipment:
    eyes: ClothingEyesGlassesSecurity
    id: PrisonGuardPDA
    ears: ClothingHeadsetPrisonGuard #DeltaV
