- type: job
  id: Borg
  name: job-name-borg
  description: job-description-borg
  playTimeTracker: JobBorg
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 216000 #60 hrs
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for higher risk roles
  canBeAntag: false
  icon: JobIconBorg
  supervisors: job-supervisors-rd
  jobEntity: PlayerBorgGeneric
