- type: antag
  id: Nukeops
  name: roles-antag-nuclear-operative-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # DeltaV - 30 hours
  - !type:DepartmentTimeRequirement # DeltaV - engi dept time requirement
    department: Engineering
    time: 7200 # DeltaV - 2 hours
  - !type:RoleTimeRequirement # DeltaV - salvage time requirement
    role: JobSalvageSpecialist
    time: 7200 # DeltaV - 2 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 36000 # DeltaV - 10 hours
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Antag roles
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsMedic
  name: roles-antag-nuclear-operative-agent-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-agent-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 108000 # DeltaV - 30 hours
  - !type:DepartmentTimeRequirement # DeltaV - Medical dept time requirement
    department: Medical
    time: 36000 # DeltaV - 10 hours
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Antag roles
  guides: [ NuclearOperatives ]

- type: antag
  id: NukeopsCommander
  name: roles-antag-nuclear-operative-commander-name
  antagonist: true
  setPreference: true
  objective: roles-antag-nuclear-operative-commander-objective
  requirements:
  - !type:OverallPlaytimeRequirement
    time: 216000 # DeltaV - 60 hours
  - !type:DepartmentTimeRequirement # DeltaV - Security dept time requirement
    department: Security
    time: 36000 # DeltaV - 10 hours
  - !type:DepartmentTimeRequirement # DeltaV - Command dept time requirement
    department: Command
    time: 36000 # DeltaV - 10 hours
  - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Antag roles
  guides: [ NuclearOperatives ]

#Nuclear Operative Commander Gear
- type: startingGear
  id: SyndicateCommanderGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    neck: SyndicateWhistle
    outerClothing: ClothingOuterHardsuitSyndieCommander
  #inhand: # DeltaV - Prevent commander spawning with the declaration of war
  #  - NukeOpsDeclarationOfWar

#Nuclear Operative Medic Gear
- type: startingGear
  id: SyndicateOperativeMedicFull
  parent: SyndicateOperativeGearFull
  equipment:
    eyes: ClothingEyesHudSyndicateAgent
    outerClothing: ClothingOuterHardsuitSyndieMedic
    shoes: ClothingShoesBootsMagSyndie
    id: SyndiAgentPDA
    belt: ClothingBeltMilitaryWebbingMedFilled
  storage:
    back:
    - SyndiHypo
    - BoxSurvivalSyndicate
    - SawAdvanced
    - Cautery
    - CombatKnife
    - WeaponPistolViper
    - PinpointerSyndicateNuclear
    - HandheldHealthAnalyzer
    - CombatMedipen
    - DeathAcidifierImplanter

#Lone Operative Gear
- type: startingGear
  id: SyndicateLoneOperativeGearFull
  parent: SyndicateOperativeGearFull
  equipment:
    pocket2: BaseUplinkRadio60TC
