- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    # Echo Station: Remove most time requirements
#    - !type:DepartmentTimeRequirement
#      department: Medical
#      time: 21600 # 6 hrs
#    - !type:RoleTimeRequirement # DeltaV - JobSecurityOfficer time requirement
#      role: JobSecurityOfficer
#      time: 21600 # DeltaV - 6 hrs
    - !type:WhitelistRequirement # Echo Station: Require server whitelisting for all Security roles
  startingGear: CorpsmanGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  #- Brig #Delta V: Removed brig access
  - Maintenance
  - Service # The rest of security has this access.
  - External
  - Corpsman
  - Cryogenics # The rest of security also gets this access.
  extendedAccess:
  - Chemistry
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: CorpsmanGear # see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml for "BrigmedicGear"
  equipment:
#    eyes: ClothingEyesHudMedical
    outerClothing: ClothingOuterCoatLabCorpsman
    id: CorpsmanPDA
    ears: ClothingHeadsetBrigmedic
    belt: ClothingBeltCorpsmanWebbingFilled
    pocket1: WeaponPistolMk58Nonlethal
